name: Continious Integration Main

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continious Integration Main
    runs-on: ubuntu-latest

    steps:
      - name: "Publish to NPM"
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
