name: Continious Integration

on:
  push:
    branches:
      - main

jobs:
  ci:
      - name: "Publish to NPM"
      uses: JS-DevTools/npm-publish@v2
      with:
        token: ${{ secrets.NPM_TOKEN }}

