name: Test

on:
on:
  push:
    branches:
      - develop

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test

      - name: "Run tests coverage"
        run: npm run jest --coverage

      - name: "Run eslint"
        run: npm run lint
