name: Continious Integration Main

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continious Integration Main
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v3

      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: "19"

<<<<<<< HEAD
      - name: Install dependencies
        run: npm i
        
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
=======
      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test

      - name: "Run eslint"
        run: npm run lint
>>>>>>> 79ab257f0ea4c19647910da21aaba719490be1f9
