name: Automate Library Versioning

on:
  push:
    branches:
      - staging

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Bump version
      run: |
        git config --local user.email "romain.danizel.pro@gmail.com"
        git config --local user.name "Meanzar"
        npm version patch -m "Bump version to %s [skip ci]"

    - name: Push changes to staging
      run: git push --set-upstream origin HEAD:staging
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1.13.0
      with:
        name: Release ${{ steps.package_version.outputs.version }}
        tag: ${{ steps.package_version.outputs.version }}
        token: ${{ secrets.MY_PERSONAL_TOKEN }}
        body: "Release notes for ${{ steps.package_version.outputs.version }}"
        draft: false
        prerelease: false
